### ISSUE TITLE
save-state and set-output are deprecated 

### ISSUE THREAD

**Issue by iTrooz** [hendrikmuhs/ccache-action#106]
Github issued a blog post yesterday deprecating `save-state` and `set-output` (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and started to issue warnings on actions

Example of such warnings : https://github.com/WerWolv/ImHex/actions/runs/3234815935

**Comment by hendrikmuhs** [comment]
Thanks for the heads up. According to the blog this issue should fix itself with an update of actions/core and a new release.

**Comment by n3world** [comment]
I think https://github.com/einblick-ai/cube/pull/171 resolves this.

**Comment by iTrooz** [comment]
I think this got fixed indeed, I do not have the warnings anymore, thanks !
