### ISSUE TITLE
can't save ccache in window

### ISSUE THREAD

**Issue by sunflower-knight** [hendrikmuhs/ccache-action#144]
Cache location                  Local disk: "D:\\a\\yalantinglibs\\yalantinglibs/.sccache"
Save cache using key "sccache-windows_msvc-Debug-ssl( OFF )-arch-amd64-20[23](https://github.com/alibaba/yalantinglibs/actions/runs/4710430215/jobs/8354059828?pr=264#step:15:24)-04-16T00:17:33.507Z".
Warning: Saving cache failed: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

after compile , ccache can't be saved in right way

**Comment by sunflower-knight** [comment]
I use windows+msvc+cmake+sccach
after building, my cache can't be save.

**Comment by sunflower-knight** [comment]
I fork it and change something
I try to modify the path 
```ts
async function configure(ccacheVariant : string) : Promise<void> {
  const ghWorkSpace = process.env.GITHUB_WORKSPACE || "unreachable, make ncc happy";
  const maxSize = core.getInput('max-size');
  
  if (ccacheVariant === "ccache") {
    await execBash(`ccache --set-config=cache_dir='${path.join(ghWorkSpace, '.ccache')}'`);
    await execBash(`ccache --set-config=max_size='${maxSize}'`);
    await execBash(`ccache --set-config=compression=true`);
    core.info("Cccache config:");
    await execBash("ccache -p");
  } else {
    const options = `SCCACHE_IDLE_TIMEOUT=0 SCCACHE_DIR='${ghWorkSpace}\\.sccache' SCCACHE_CACHE_SIZE='${maxSize}'`;
    await execBash(`env ${options} sccache --start-server`);
  }

}
```
```ts
  const options = `SCCACHE_IDLE_TIMEOUT=0 SCCACHE_DIR='${ghWorkSpace}\\.sccache' SCCACHE_CACHE_SIZE='${maxSize}'`;
```

And here is the output in the end 

Cache location                  Local disk: "D:\\a\\yalantinglibs\\yalantinglibs\\.sccache"
  Version (client)                0.4.1
Save cache using key "sccache-windows_msvc-Debug-ssl( OFF )-arch-x86-20[23](https://github.com/sunflower-knight/yalantinglibs/actions/runs/4712621535/jobs/8357780757#step:17:23)-04-16T09:43:41.001Z".
Warning: Saving cache failed: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

**Comment by SchrodingerZhu** [comment]
Why this is marked as completed? what is the fix?
