### ISSUE TITLE
Groping of the apt Install logs

### ISSUE THREAD

**Issue by berlin4apk** [hendrikmuhs/ccache-action#15]
https://github.com/hendrikmuhs/ccache-action/blob/1ed7eb5b4b2afeceab143d0caa0d7fa87c33047b/src/restore.ts#L9

Can we please make a group of the Install logs of ccache?

https://pakstech.com/blog/github-actions-workflow-commands/#log-grouping

And output the ccache stats before the rest?
So we can direct see how good was it it the last run.

**Comment by hendrikmuhs** [comment]
> https://github.com/hendrikmuhs/ccache-action/blob/1ed7eb5b4b2afeceab143d0caa0d7fa87c33047b/src/restore.ts#L9
> 
> Can we please make a group of the Install logs of ccache?

Sounds good. Feel free to create a PR for it.

> 
> https://pakstech.com/blog/github-actions-workflow-commands/#log-grouping
> 
> And output the ccache stats before the rest?
> So we can direct see how good was it it the last run.

I am not sure I understand this request, what do you mean by "rest"?
Note that the execution order is provided by githubs workflow execution engine.
