### ISSUE TITLE
The ccache directory space grows too fast for a single upload

### ISSUE THREAD

**Issue by nautaa** [hendrikmuhs/ccache-action#166]
For push-frequent repositories, old ccache is hardly ever used again after a while. However, the ccache directory still downloads the old cache directory and adds new cache items to it, and finally uploads the whole directory to the github action cache. So the ccache directory space grows too fast for a single upload. Is there a mechanism to avoid uploading the old cache in ccache directory?

**Comment by nautaa** [comment]
@hendrikmuhs

**Comment by hendrikmuhs** [comment]
You can limit the size using the `max-size` parameter.

**Comment by nautaa** [comment]
Thanks for your reply.
