### ISSUE TITLE
preferred way for configuring ccache

### ISSUE THREAD

**Issue by janisozaur** [hendrikmuhs/ccache-action#2]
Using this action, what's the preferred way to change ccache configuration, e.g. altering cache size?

https://github.com/hendrikmuhs/ccache-action/blob/7cbd38d6eef8ad90a754e793d8fdc9dbb97254ad/src/restore.ts#L48

has the defaults hardcoded, should I alter the file after the action has executed? Is there an output variable to store the file path? Should I use ccache's support for setup with env variables?

I'm comfortable with doing any of those, but wanted to reach out in case there's some preference already. Ideally though, there would be an input to this action to be passed on to ccache configuration.

**Comment by hendrikmuhs** [comment]
> Ideally though, there would be an input to this action to be passed on to ccache configuration.

I think that's the way to go and shouldn't be too hard to implement. Do you think you can manage and create a PR?

**Comment by janisozaur** [comment]
I can give it a try this out next week

**Comment by hendrikmuhs** [comment]
I implemented it: https://github.com/hendrikmuhs/ccache-action/commit/7a464b8f54f1e1b78e7eb9d0272bc83072959235

Let me know if it does not work.

**Comment by hansfn** [comment]
Maybe document this new key, "max-size", in the readme?
