### ISSUE TITLE
usage in Docker: upgrade to ccache 4.4.2 and add a secondary storage backend (bazel-remote or Redis storage)

### ISSUE THREAD

**Issue by berlin4apk** [hendrikmuhs/ccache-action#30]
can you please upgrade the ccache to 4.4.2 and add a secondary storage backend?

so ccache will be usibil inside of a docker build run, running as github action workflow.

**Comment by hansfn** [comment]
Why is this issue open, when the commit above claims to fix it? (Sorry about repeating myself.)

**Comment by hendrikmuhs** [comment]
fixed in #54
