### ISSUE TITLE
Make Save optional

### ISSUE THREAD

**Issue by AzHicham** [hendrikmuhs/ccache-action#39]
Hello, 
First of all, thank you for you work, it's a really cool action, that can save a lot of time !! 

I would like to know if it's possible to make the saving optional here is the typical use case for me : 
- load & save cache on dev (ie when merging PR) 
- only load cache when running CI on a PR -> So we avoid using github cache (limited to 10Go only) and make the cache on dev branch too old (and then deleted). This works (for me) because loading cache on PR use cache located on dev branch (if base branch is dev ...)

I could also make a PR if you want :)

**Comment by hendrikmuhs** [comment]
Sounds like a useful addition. It would be good if it integrates nicely with common workflow logic. I therefore think of a workflow environment variable that if set skips the save part.

**Comment by AzHicham** [comment]
That sounds great !!! 
that would be a Boolean var env ?

**Comment by hendrikmuhs** [comment]
sorry again for the late answer, yes a boolean env. However, env variables are just based on strings, so either it is there or not and you don't need to check the value.

**Comment by hansfn** [comment]
Why is this issue open, when the commit above claims to fix it?

**Comment by hendrikmuhs** [comment]
fixed in #54
