### ISSUE TITLE
Support Windows Mingw (32 bits preferred)

### ISSUE THREAD

**Issue by PibePlayer** [hendrikmuhs/ccache-action#5]

**Comment by ghutchis** [comment]
It would be great to use https://github.com/cristianadam/ccache/releases/ for Windows - it's not an official release, but it's regularly updated.

**Comment by hendrikmuhs** [comment]
I have to lower expectations: I don't have windows build environment and there is not just one, but several different compilers. If someone is looking into it and can provide a PR, I happily merge it.

**Comment by jonashaag** [comment]
#50

**Comment by hendrikmuhs** [comment]
fixed in #50
