### ISSUE TITLE
Unable to locate executable file: sudo

### ISSUE THREAD

**Issue by Shatur** [hendrikmuhs/ccache-action#6]
I have the following error on Windows:

```
Error: Unable to locate executable file: sudo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

Does Windows supported by this action?

**Comment by hendrikmuhs** [comment]
Windows is not supported.

Please note: Windows support depends on ccache, too. At the time of writing ccache does not support msvc. See https://ccache.dev/platform-compiler-language-support.html

**Comment by Shatur** [comment]
Got it, thanks!
