### ISSUE TITLE
Invalid input option 'save'

### ISSUE THREAD

**Issue by AzHicham** [hendrikmuhs/ccache-action#67]
Hello, 

I tried to use the newly introduced input option 'save' to disabled saving cache when some conditions are met. 
Unfortunately I get the following warning : 
Warning: Unexpected input(s) 'save', valid inputs are ['key', 'max-size'] 
workfow run : https://github.com/hove-io/navitia/runs/6292655767?check_suite_focus=true#step:4:38 

I check that the latest version of ccache-action is used : https://github.com/hove-io/navitia/runs/6292655767?check_suite_focus=true#step:1:56 

Thank you for your help and tour work

**Comment by jonashaag** [comment]
You are using an old version
