### ISSUE TITLE
How can I use it with custom compiler?

### ISSUE THREAD

**Issue by ntosis** [hendrikmuhs/ccache-action#85]
Hi, how can I use ccache in github actions with custom compiler like "gcc arm none eabi" ?

**Comment by hendrikmuhs** [comment]
The only thing I could find is this: https://github.com/ccache/ccache/discussions/426

I think this is a matter on how you call ccache, the above link manipulates `PATH` and uses symlinks.

**Comment by hendrikmuhs** [comment]
Closing due to lack of further feedback.
